language: php
php:
- '5.6'
- '7.0'
- hhvm
- nightly
before_script:
    - cp phpunit.xml.dist phpunit.xml
    - flags=""
    - composer install $flags
script: vendor/bin/phpunit
notifications:
  slack: faunusaff:3i5oVlDHMuZXXHFkTe0glJeP
